# Generated by Django 4.2.10 on 2024-03-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to='report_files/')),
                ('residence_type', models.CharField(max_length=100)),
                ('residence', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('floor', models.IntegerField()),
                ('room', models.CharField(max_length=100)),
                ('submission_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed')], default='pending', max_length=10)),
            ],
        ),
    ]
