# Generated by Django 4.2.10 on 2024-04-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_report_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="admin_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("In Progress", "In Progress"),
                    ("Resolved", "Resolved"),
                ],
                default="New",
                max_length=20,
            ),
        ),
    ]
