# Generated by Django 4.2.10 on 2024-04-19 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0004_report_admin_message_alter_report_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Residence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("residence_type", models.CharField(max_length=200)),
                ("residence", models.CharField(max_length=200)),
                ("building", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("residence", models.CharField(max_length=200, null=True)),
                ("building", models.CharField(max_length=200, null=True)),
                ("floor", models.CharField(max_length=100, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserResidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("residence", models.CharField(max_length=100)),
                ("building", models.CharField(max_length=100)),
                ("floor", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.AddField(
            model_name="report",
            name="report_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="report",
            name="building",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="floor",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="room",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
