# Generated by Django 4.2.10 on 2024-04-27 05:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "reports",
            "0005_residence_userprofile_userresidence_delete_document_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserResidence",
        ),
    ]
